### ISSUE TITLE
Aggregate public keys

### ISSUE THREAD

**Issue by kokeshiM0chi** [line/ostracon#205]
## Summary
Computational complexity is less when public keys are aggregated at the time of aggregation signature creation rather than at verification.

## Problem Definition
If you sign the same message and aggregate the signatures, use this function for verification. 
https://github.com/herumi/bls-eth-go-binary/blob/master/bls/bls.go#L843
However, this internally aggregates the public key array for each verification. This takes time, so if you aggregate the public keys when creating the aggregate signature and use that key, we only need to aggregate the keys once.

## Proposal
We can use this function to aggregate public keys
https://github.com/herumi/bls-eth-go-binary/blob/master/bls/bls.go#L461

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by torao** [comment]
(accidentally closed by bot😱)

**Comment by torao** [comment]
This suggestion doesn't work well since the set of Validators that generate signatures changes dynamically from round to round. This is because if it were to do so, it would be necessary to additionally verify that the aggregated public key $\pi$ received with an aggregated signature $\sigma$ is correct. More precisely, an additional requirement arises to generate an aggregate public key $\pi'$ from the public keys $p_i$ assumed by the verifier $x$ for $\sigma$ and to verify that $\pi = \pi'$. This would require more processing than is currently implicit and therefore has no performance benefit.
