### ISSUE TITLE
Make VRF available on the remote signer

### ISSUE THREAD

**Issue by zemyblue** [line/ostracon#50]
`tm-signer-harness` of Tendermint doesn't support VRF signature.
Thus, we need to ready alternative way.

1. Use other HSM supporting VRF
2. Modify [`tmkms`](https://github.com/iqlusioninc/tmkms)
3. Etc

### Implementation of Tendermint
* Tendermint's remote signer is implemented in [`tools/tm-signer-harness`](https://github.com/line/tendermint/tree/master/tools/tm-signer-harness)

* YubiHSM 2 device client for Tendermint : https://github.com/iqlusioninc/yubihsm.rs

**Comment by torao** [comment]
(accidentally closed by bot😱)

**Comment by torao** [comment]
As it is difficult to add VRF functionality to the current HSM product, which is a hardware circuit, other than designing the circuit ourselves and implementing VRF. Therefore, instead of using HSM-based `tmkms`, we have decided to implement an SGX-based KMS to replace `tmkms`. The following PR enables the use of a secure KMS that supports VRF.
https://github.com/line/ostracon/pull/417
